# foxglove_msgs/msg/Color
# A color in RGBA format

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from pycdr2.types import float64

@dataclass
class Color(IdlStruct, typename='foxglove_msgs/Color'):
    # Red value between 0 and 1
    r: float64 = 0

    # Green value between 0 and 1
    g: float64 = 0

    # Blue value between 0 and 1
    b: float64 = 0

    # Alpha value between 0 and 1
    a: float64 = 0