# foxglove_msgs/msg/CubeAttributes
# Data specifying the visual appearance of a cube or rectangular prism

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from ..geometry_msgs.Pose import Pose
from ..geometry_msgs.Vector3 import Vector3
from .Color import Color

@dataclass
class CubeAttributes(IdlStruct, typename='foxglove_msgs/CubeAttributes'):
    # Position of the center of the cube and orientation of the cube
    pose: Pose = Pose()

    # Size of the cube along each axis
    size: Vector3 = Vector3()

    # Color of the arrow
    color: Color = Color()