# foxglove_msgs/msg/FrameTransforms
# An array of FrameTransform messages

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from pycdr2.types import sequence
from .FrameTransform import FrameTransform
from .. import default_field

@dataclass
class FrameTransforms(IdlStruct, typename='foxglove_msgs/FrameTransforms'):
    # Array of transforms
    transforms: sequence[FrameTransform] = default_field([])