# foxglove_msgs/msg/GeoJSON
# GeoJSON data for annotating maps

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct

@dataclass
class GeoJSON(IdlStruct, typename='foxglove_msgs/GeoJSON'):
    # GeoJSON data encoded as a UTF-8 string
    geojson: str = ''