# foxglove_msgs/msg/KeyValuePair
# A key with its associated value

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct

@dataclass
class KeyValuePair(IdlStruct, typename='foxglove_msgs/KeyValuePair'):
    # Key
    key: str = ''

    # Value
    value: str = ''