# foxglove_msgs/msg/Point2
# A point representing a position in 2D space

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from pycdr2.types import float64

@dataclass
class Point2(IdlStruct, typename='foxglove_msgs/Point2'):
    # x coordinate position
    x: float64 = 0

    # y coordinate position
    y: float64 = 0
