# foxglove_msgs/msg/PrimitiveDeletion
# Command to remove previously published markers

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from pycdr2.types import uint8
from ..builtin_interfaces.Time import Time
from enum import Enum

class DeletionAction(Enum):
    MATCHING_ID=0
    ALL=1

@dataclass
class PrimitiveDeletion(IdlStruct, typename='foxglove_msgs/PrimitiveDeletion'):
    # Timestamp of the marker. Only matching markers earlier than this timestamp will be deleted.
    timestamp: Time = Time()

    # Type of deletion action to perform
    type: uint8 = 0

    # Numeric identifier which must match if `kind` is `MATCHING_ID`.
    id: str = ''
