# foxglove_msgs/msg/SceneEntities
# An update to the entities displayed in a 3D scene

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from pycdr2.types import sequence
from .SceneEntityDeletion import SceneEntityDeletion
from .SceneEntity import SceneEntity
from .. import default_field

@dataclass
class SceneEntities(IdlStruct, typename='foxglove_msgs/SceneEntities'):
    # Scene entities to delete
    deletions: sequence[SceneEntityDeletion] = default_field([])

    # Scene entities to add or replace
    entities: sequence[SceneEntity] = default_field([])
