# foxglove_msgs/msg/SpherePrimitive
# A primitive representing a sphere or ellipsoid

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from ..geometry_msgs.Pose import Pose
from ..geometry_msgs.Vector3 import Vector3
from .Color import Color

@dataclass
class SpherePrimitive(IdlStruct, typename='foxglove_msgs/SpherePrimitive'):
    # Position of the center of the sphere and orientation of the sphere
    pose: Pose = Pose()

    # Size (diameter) of the sphere along each axis
    size: Vector3 = Vector3()

    # Color of the sphere
    color: Color = Color()
