# foxglove_msgs/msg/Vector2
# A vector in 2D space that represents a direction only

# Generated by https://github.com/foxglove/schemas

from dataclasses import dataclass
from pycdr2 import IdlStruct
from pycdr2.types import float64

@dataclass
class Vector2(IdlStruct, typename='foxglove_msgs/Vector2'):
    # x coordinate length
    x: float64 = 0

    # y coordinate length
    y: float64 = 0
